name: workflow_executor_env
channels:
  - eoepca
  - conda-forge
  - terradue
  - defaults
dependencies:
  - cwl-wrapper=0.0.4
  - click=7.1.2=pyh9f0ad1d_0
  - fastapi=0.61.1=py_0
  - python-kubernetes=12.0.0=pyh9f0ad1d_0
  - uvicorn=0.12.1=py38h32f6830_0
